### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by ireenna** [ireenna/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by suppper-programmer** [comment]
Hello! I am one of the most future-oriented people, a business magnate, investor, entrepreneur, inventor and engineer. Throughout my life I have been a part of many business ventures but currently I am full-time involved in Tesla Inc., SpaceX and SolarCity. I am ambitious for the future and I believe that in my lifetime people will be able to have commercial space flights to Mars.
“If things are not failing, you are not innovating enough.” - Elon Musk.
